### ISSUE TITLE
USB protocol information

### ISSUE THREAD

**Issue by maks** [EspoTek/Labrador#1]
Chris I realise you've just published the code and are still in the middle of the crowdfunding campaign, but when you get the chance it would be great if you could include some notes on the usb protocol used to talk to the board? My C++ isn't great but looks like in isodriver.cpp you are doing Isochronous transfers?

The reason I ask is that alot of schools in my area (here in SE Melb) are going with Chromebooks as 1:1 devices and it would be great to be able to use Labrador boards at the schools (primary and secondary) and for kids to be able to use their chromebooks in extra-cirrricular electronics activities too (eg. library maker spaces etc). I've done Chrome app dev in the past and would be keen to have a go, the excellent IDE that Espruino did as a Chrome App is a great example of what is possible.

**Comment by EspoTek** [comment]
Hi Maks!
The real-time elements (scope, logic analyzer) use an isochronous IN pipe (750 bytes per frame, 1000 frames per second).
Everything else uses the (bidirectional) default control endpoint (0x00).
winusbdriver contains the actual calls to libusb; the "driver" variable in isoDriver is just a pointer to this.

No idea how hard it is to port this stuff to ChromeOS (should be easy if it's just a flavour of Linux), but good to hear that schools aren't still using those netbooks from the Gillard era!  Horrible memories of the 30 minute login times coming back.

Shoot us an email if you're interested in looking at the hardware in the flesh, by the way.  admin@espotek.com
I'm in SE Melb too (Knox area).

-Chris
