### ISSUE TITLE
Make the PCB a little more breadboard compatible?

### ISSUE THREAD

**Issue by tardate** [EspoTek/Labrador#10]
I've been playing with a batch 1 backer edition PCB (you can [see my notes here](https://github.com/tardate/LittleArduinoProjects/tree/master/Equipment/Labrador)).

I was able to stick it on a breadboard with a minor bend of the PSU pins, and then the PSU is on the breadboard power rail and all the pins on the left side of the board are routed to the breadboard. This is pretty convenient for testing and experimentation.

Although the board will never be fully breadboard-compatible in its current form, there's one minor change that might be worth considering: nudge the PSU pins up or down 50mil and then the PCB would plug directly into a standard MB104 breadboard with no pin bending.

**Comment by EspoTek** [comment]
You're absolutely right.   I didn't actually believe you until I tried it myself!
The fact that the pins bend when being plugged into a breadboard is definitely a bug.  Fortunately not a critical one, but still not ideal...  It was designed to go in smoothly; I even used a 50mil grid to ensure it was perfectly accurate.  Looks like at some stage that grid god messed up, though.

I'll have to fix that up for the next batch (also will ensure they use a better opamp to reduce noise a bit).
