### ISSUE TITLE
Cannot See Device When Plugged In (Mac 10.14.8, RPi Zero)

### ISSUE THREAD

**Issue by joedski** [EspoTek/Labrador#101]
Hello, I am not seeing my Labrador when I plug it into my computer.  I have tried the following, both with nothing shorted and in bootloader mode.

- Mac 10.14.8 on 2012 MBP:
   - USB 2 port directly on computer
   - USB 3 port on dock
- Raspberry Pi Zero W:
   - Data-enabled USB port
   - Data-enabled USB port via USB 2 hub, Labrador as only device plugged into the hub

Across all of the above, I've tried:

- In bootloader mode
- Not in bootloader mode

Using `lsusb` did not show any changes before and after plugging the device in.  The power LED does turn on, but I don't see anything else happen anywhere.  I've ensured that the cable I used can transmit data, as I have used it to interface with a NodeMCU board.

Is there anything else I could try that I might have missed in the docs?

**Comment by EspoTek** [comment]
If `lsusb` shows no change and the cable can transfer data, then the only possible explanation is that your board is DOA.

Please contact me at `admin@espotek.com` with your order info and I'll have a replacement shipped out to you free of charge.

And thanks for being descriptive with all the troubleshooting steps - no back and forth this way.
