### ISSUE TITLE
Trigger not working on Double Sample Rate?

### ISSUE THREAD

**Issue by AlabasterAxe** [EspoTek/Labrador#102]
Hi, not sure if this is a known limitation but the trigger functionality doesn't seem to be working for me when running double sample rate. No issues with triggering in standard mode.

Really enjoying it overall though!

Thanks,

**Comment by EspoTek** [comment]
Wow, that's not great (especially considering https://github.com/EspoTek/Labrador/issues/98 also).

I'm currently away holiday, but will make sure to fix up the Double Sample Rate mode when we get back.

**Comment by EspoTek** [comment]
Fixed in d04da3748d5e446eb385b115ab5aa5d17da2ee39
