### ISSUE TITLE
DAQ output compatible with LTspice PWL format

### ISSUE THREAD

**Issue by phorensic** [EspoTek/Labrador#105]
Hello,
I am trying to capture data on the Labrador and then import it into LTspice to feed into a voltage source. LTspice uses a format called PWL (Piece Wise Linear). Format described here on page 4 and 5 - https://www.ieee.li/pdf/viewgraphs/ltspice_piece_wise_linear_voltage_sources.pdf.

The DAQ output in the Labrador software makes a csv file, which is great, but it seems to contain only voltage values, and no timestamps. Is that correct? Can we add the format that LTspice likes? Apparently some bench scopes already can do it.

Thanks,
Matt

**Comment by EspoTek** [comment]
Hey, I had no idea there was an industry standard format.
It doesn't look like it'll be too difficult to implement either.
I'll put this in during the next major development session.  Importing as well as exporting would be great too.

**Comment by phorensic** [comment]
Thanks!
