### ISSUE TITLE
higher sample rate to see adressable LED data. SPI, I2C, Serial.

### ISSUE THREAD

**Issue by perigalacticon** [EspoTek/Labrador#108]
This would be a perfect device to use to diagnose addressable led data such as WS2812B, but it runs at 800kHz.  Can't tell you how many times I wanted to get a good look at what is causing glitching in certain installations.  Having a small battery or 5V powered portable scope would be great for this.  Not sure how fast you need to sample to get 800kHz but that would be really nice.

**Comment by EspoTek** [comment]
Try Labrador's logic analyzer.  It works exactly like the oscilloscope, but takes 3 million samples per second (so you'd get 3-4 samples per bit at 800kHz!)

The downside is that each sample is only one bit - so you can't see the exact analog waveform of the signal, just if it's on or off.

If you need that level of detail in a portable device, I've heard nothing but positive things about Picoscope's products:
https://www.picotech.com/
They're obviously a bit more than $29, though!
