### ISSUE TITLE
the negative part of the signal clips

### ISSUE THREAD

**Issue by faisally** [EspoTek/Labrador#117]
Hi,
I have a question regarding the max input voltage could the oscilloscope read, I ordered ESPOTEK yesterday and connected the oscilloscope to an external function generator to test how it displays the signal, when I increased the amplitude to more than 3V  (-3V to 3V sin wave)the negative part of the signal clips, could you help me to figure out why this happens?
Thank you,

**Comment by phr0gger** [comment]
Same as #113?
