### ISSUE TITLE
Working on Win 10 - but not on Android 8.0

### ISSUE THREAD

**Issue by Fixador** [EspoTek/Labrador#119]
Hi, fine on Win 10  , but using via an known good OTG into (1) Android 8.0 on a ZL10, and (2) Titan 4 . Android 5.01. The OTG lead was tested on both androids into a mouse. Labrador reports on both of the Androids  at the top of the screen that device not connected - red led is illuminated on pcb. Suggestions please

**Comment by superfrink** [comment]
Not sure if it is the same issue but I had to try four different micro USB cables until finding one that worked.

The setup was Android 9 with USB C -> OTG adapter to USB A -> USB cable to micro B -> Labrador.
