### ISSUE TITLE
Device driver not installed

### ISSUE THREAD

**Issue by iryek219** [EspoTek/Labrador#122]
I cannot connect the board on Windows 10 64bit, Windows 7 32bit, and Ubuntu 18.04 64bit.
Both Windows systems are based on Intel cpu and Ubuntu AMD.

On connecting the board through USB, I see that driver of 'USBGobindar dummy device' is not installed.
The hardware id of the device is like below:

    VID_03EB&PID_A000&REV_0200
   
Please help me setup the board.

**Comment by EspoTek** [comment]
Can you please provide the output of lsusb on the Ubuntu system, before and after connecting the board?

**Comment by iryek219** [comment]
Before connecting the device

hwan@hp-g6:~$ lsusb
Bus 002 Device 003: ID 0c45:6458 Microdia 
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

After

hwan@hp-g6:~$ lsusb
Bus 002 Device 003: ID 0c45:6458 Microdia 
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 024: ID 03eb:a000 Atmel Corp. 
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by EspoTek** [comment]
This is a serious error.  It looks like the latest batch of boards were misconfigured at the factory.
I'm patching the software now to detect and rectify this.

**Comment by EspoTek** [comment]
Please download the latest version of the software (released today).  It has a new function in it that will detect the configured boards and automatically repair them.

Thank you for sharing the bug report.
Please let me know if this does not fix the issue.

**Comment by iryek219** [comment]
Let me confirm that the latest release works. Now, the device connects without any problem. And, I've done the simple tutorial of voltage divider. 
Thanks for your quick actions!!!

**Comment by EspoTek** [comment]
Not a worry.  The fix wasn't too difficult, just needed a customer to explain the problem.  So thank you for your report.  :)
