### ISSUE TITLE
Suddenly unable to connect Labrador device 

### ISSUE THREAD

**Issue by lesley-sudo** [EspoTek/Labrador#125]
Hello - I had my board connected and everything was fine and I was using it successfully as an oscilloscope. Then I took a break and came back and the device is no longer recognized/connected. I did not change anything, and since it was working before, I know it is not the cable. I uninstalled and reinstalled the firmware. This didn't help. And I unplugged it and left it for a while and then tried again and this still didn't help. I found the connection in my device manager (running on a windows system) and it says "Unknown USB device (device descriptor request failed)". When I try to update the driver for this "unknown" device, the Labrador driver isn't found even though I just tried reinstalling and all the driver boxes were checked in the process. I'm wondering why this suddenly happened and if anyone has any suggestions to get this working again. Thank you!!

**Comment by EspoTek** [comment]
If it can't get the device descriptors, then either your board or your USB cable is physically damaged.
Do you have another cable you can try, or another device you can try with your cable?
