### ISSUE TITLE
Feature Request: Sigrok integration

### ISSUE THREAD

**Issue by emosenkis** [EspoTek/Labrador#132]
It would be amazing to be able to capture data directly into [Sigrok](https://sigrok.org/). I've managed to dump it to CSV then load it in Sigrok, but I think Labrador could really benefit from Sigrok's mature [PulseView](https://sigrok.org/wiki/PulseView) UI and analysis capabilities.

**Comment by EspoTek** [comment]
I completely agree with you that it would add a huge amount of value to Labrador, especially for the logic analyser part.
Unfortunately, I made some bad upfront design decisions that make Sigrok integration far from trivial.
Perhaps in Labrador 2.0...

**Comment by techdragon** [comment]
@EspoTek Could you outline some of these design issues? ... I saw an old post about Librador and an API in reference to potential Sigrok support and I see old code for it here still... I adore the idea of having a few cheap 12bit Oscilloscopes for when I need that little extra, and it would be utterly wonderful to just be able to throw everything into Sigrok with my other scopes and such.

**Comment by nerdx86** [comment]
@EspoTek @techdragon Was there any further conversation on this?  I or my team may be able to throw some help this way as well?

**Comment by EspoTek** [comment]
Nah mate, nothing to add.

You're welcome to have a crack, but this would be a serious undertaking!
