### ISSUE TITLE
Calibration Issues

### ISSUE THREAD

**Issue by wtpearson** [EspoTek/Labrador#133]
Hello, I'm having issues getting my new board calibrated.  Channel 2 has a "permanent" +1.7v offset and is noisier than channel 1. Grounding both channels to the USB shield (or any other ground) helps with the noise a bit but I still can't calibrate due to the offset. 
Not grounded:
![image](https://user-images.githubusercontent.com/75443492/101955182-5b3c2400-3bcb-11eb-9631-974636cc66ac.png)

Grounded:
![image](https://user-images.githubusercontent.com/75443492/101955224-70b14e00-3bcb-11eb-823b-8f4b71042ab0.png)

Thanks.

**Comment by EspoTek** [comment]
Hi mate.  The channels should float to around 1.7V when no input is connected.
Are you absolutely sure you're grounding the correct pins?
Make sure you're using the DC inputs, *not the AC*, and double check you're familiar with the pinout.
https://github.com/EspoTek/Labrador/wiki/Pinout

Top row is CH2, bottom is CH1.

**Comment by wtpearson** [comment]
Oof, yes I should have examined the pinout more carefully.  I was using the incorrect channels for calibration.  Thanks for the assist.
