### ISSUE TITLE
Windows 7 drivers not found after install

### ISSUE THREAD

**Issue by Ikemeister** [EspoTek/Labrador#134]
Can't get this unit to work with my Pixel 3a XL so thought I'd try it out on my Windows 7 PC. 
![1 Security Warnng](https://user-images.githubusercontent.com/8944511/101960857-5c268300-3bd6-11eb-9cdb-f4ca3b1acd67.JPG)
Ran the installation in spite of the warning. The install proceeds to the Prerequisites setup screen:
![2 Prerequisites](https://user-images.githubusercontent.com/8944511/101960993-b9223900-3bd6-11eb-89e1-03dbb2ecdca7.JPG)
I left them all selected:
![3 Prerequisite Selection](https://user-images.githubusercontent.com/8944511/101961049-e2db6000-3bd6-11eb-89ec-b45f989ebc6b.JPG)
Bootloader installed:
![4 Bootloader Installed](https://user-images.githubusercontent.com/8944511/101961078-f7b7f380-3bd6-11eb-815d-bcbb3dad946b.JPG)
Primary Installed:
![5 Primary Installed](https://user-images.githubusercontent.com/8944511/101961114-07cfd300-3bd7-11eb-8546-1f9b2288403d.JPG)
Misconfigured Batch Installed:
![6 Misconfigured Batch Installed](https://user-images.githubusercontent.com/8944511/101961149-1c13d000-3bd7-11eb-93ac-8376257b0a43.JPG)

I continued with the installation but the device shows up as Not Connected:
![7a Device Not Connected](https://user-images.githubusercontent.com/8944511/101961885-b7597500-3bd8-11eb-9f6a-e8eff6e8eeef.JPG)

It shows up as unknown via Device Manager:
![7 Device Manager](https://user-images.githubusercontent.com/8944511/101961236-4796ba80-3bd7-11eb-934a-1ec0b840d286.JPG)
Searched for the drivers using the documented procedure. Note that the drivers aren't found: 
![8 No driver found](https://user-images.githubusercontent.com/8944511/101961340-84fb4800-3bd7-11eb-8308-f66d887124e0.JPG)

I repeated the driver installation several times with same results. So what now? Could I perhaps explore for the drivers where they should have been installed?  Suggestions please!

**Comment by EspoTek** [comment]
Hi mate.  Under the "Details" tab, what is the value of the "Hardware IDs" property?

**Comment by Ikemeister** [comment]
*ANVSOFTWaveExtensible

**Comment by EspoTek** [comment]
That doesn't seem right.  When you unplug the Labrador, does the Unknown Device disappear?

**Comment by Ikemeister** [comment]
Nope. Still there. Should the Labrador driver disappear when the unit is disconnected?

**Comment by Ikemeister** [comment]
I checked to see what shows up when plugging the unit back in and I find another unknown device under UBC controllers. When I follow the procedure as described in the documentation, I find only Unknown Device is found:
![9 USB driver list](https://user-images.githubusercontent.com/8944511/101999214-cc053e00-3ca8-11eb-9bec-aaba02e67f0a.JPG)

**Comment by EspoTek** [comment]
Yeah, the device should not be visible under Device Manager when it's not connected.  The USB controller is a red herring, too.

When connecting, does the "USB Connected" sound play?
If not, please try the cable you have with a different device and make sure it can transmit data.
If it's not the cable, your board is faulty.

**Comment by Ikemeister** [comment]
You are correct Sir! The cable I was using and had been using for a long time, can now only be used for charging purposes. It had been working to transfer data with my PC from my old phone but with the Pixel I've been using WiFi. In the meantime one of the data leads must have broken. It's now working with another USB cable. Apologies and thanks for your suggestions.

**Comment by EspoTek** [comment]
No dramas, mate.  Thanks for the detailed information and actually following the suggestions!  Made solving the problem so much easier and more pleasant!
