### ISSUE TITLE
5V pad

### ISSUE THREAD

**Issue by skorokithakis** [EspoTek/Labrador#135]
To continue the discussion I inappropriately started on #113, I see there is a 5V pad on the "fuse bypass" pins. Since it comes straight from USB, I assume I can use it fine, I just have another question: If I use the bottom pin, do I get 5V fused? That's even more useful.

If I'm correct, could this be documented in the wiki or pinout image? I'd be happy to edit the wiki, though I'm not very knowledgeable about fuses.

**Comment by EspoTek** [comment]
That's correct, Stavros.  Good find!
The fuse is PTC resettable, by the way.  Max current is around 400mA.
