### ISSUE TITLE
.deb doesn't install on Debian Testing: no qt5-default

### ISSUE THREAD

**Issue by citroboy** [EspoTek/Labrador#138]
dpkg: dependency problems prevent configuration of espotek-labrador:
 espotek-labrador depends on qt5-default; however:
  Package qt5-default is not installed.

$ apt-cache policy qt5-default
qt5-default:
  Installed: (none)
  Candidate: (none)
  Version table:

Apparently you should be using qtchooser instead:
https://qt-kde-team.pages.debian.net/packagingqtbasedstuff.html

**Comment by EspoTek** [comment]
Honestly, I think the best solution is to just deprecate the .deb.
Linux distribution issues are a (never-ending) nightmare to handle, and the net result is that a tiny fraction of a tiny fraction of the userbase has to type one less line into the terminal when installing the software.
