### ISSUE TITLE
Issue with Multimeter

### ISSUE THREAD

**Issue by hchaudh2** [EspoTek/Labrador#146]
Also, another issue is coming up. When I click multimeter, everything goes away on the black screen and it sort of freezes up. I was trying to read the voltage and current after I made a circuit. What is the issue here?

**Comment by EspoTek** [comment]
The Multimeter mode is a software wrapper around a special mode of the oscilloscope.  Scroll out on the display until you can see the trace, and the display should unfreeze.

**Comment by hchaudh2** [comment]
I'm sorry I should have explained this better, but it doesn't necessarily freeze. The green and yellow on the black display disappears and then I can't measure the voltage or current anymore.

**Comment by EspoTek** [comment]
Yeah, I understand what you mean.  You need to zoom out the display.

**Comment by hchaudh2** [comment]
Sorry, how do I do that? I thought it was already zoomed out.

**Comment by EspoTek** [comment]
Put the mouse cursor over the display and scroll out.  You should see a trace somewhere!

**Comment by hchaudh2** [comment]
I think it worked for voltage, but when I try to get current. It says F for all values and the green/yellow disappears on the black screen.

**Comment by EspoTek** [comment]
You're using 1.1, right?  Can I ask what version of MacOS you're running?

**Comment by hchaudh2** [comment]
What do you mean by 1.1? My MacOS is version 11.2.1

**Comment by EspoTek** [comment]
I'm talking about release 1.1 of the software.  It's about 3 years old now and has some pretty major bugs still in it.  Honestly, I can't offer support for such an old build.

If you're able to update your MacOS version to 10.12 or later, I strongly recommend doing that and upgrading to the continuous release of Labrador.
Otherwise, I'd recommend either installing Windows through Bootcamp or making a bootable USB of Ubuntu.

**Comment by hchaudh2** [comment]
I have updated my MacOS version to 10.12 or later, but when I update to the continuous release of Labrador, it won't open and ends up crashing.

**Comment by EspoTek** [comment]
You can't run unsigned apps in 10.12 or later through a double-click.  Instead you need to right-click, select open, then confirm that you want to open it.

**Comment by hchaudh2** [comment]
It still won't open when I do that.

**Comment by EspoTek** [comment]
OK.  Can you please "Show Package Contents" on it, navigate to Contents->MacOS and then drag the raw executable in there onto a terminal window?  What does it say when you do that?

**Comment by hchaudh2** [comment]
% /Volumes/bin\:Labrador/Labrador.app/Contents/MacOS/Labrador
QObject::connect: No such slot bufferControl::signalGenIn(bool)
QObject::connect:  (sender name:   'signalGenGroup_CH2')
QObject::connect:  (receiver name: 'bufferDisplay')
QObject::connect: No such slot isoDriver::setWindow(int)
QObject::connect:  (sender name:   'timeBaseSlider')
QObject::connect:  (receiver name: 'controller_iso')
QObject::connect: No such slot timedTickBox::resetTimer(bool)
QObject::connect:  (sender name:   'lockPsuCheckBox')
QObject::connect:  (receiver name: 'lockPsuCheckBox')
QMetaObject::connectSlotsByName: No matching signal for on_actionRecord_triggered(bool)
QMetaObject::connectSlotsByName: No matching signal for on_actionTake_Snapshot_triggered()
Attempting to open "/Volumes/bin:Labrador/Labrador.app/Contents/MacOS/waveforms/_list.wfl"
nameBuffer =  Sin

nameBuffer =  Square

nameBuffer =  Triangle

nameBuffer =  Sawtooth

nameBuffer =  DC
newName =  "Sin"
opening "/Volumes/bin:Labrador/Labrador.app/Contents/MacOS/waveforms/Sin.tlw"
Length =  128
Divisibility =  4
List loaded!!
Attempting to open "/Volumes/bin:Labrador/Labrador.app/Contents/MacOS/waveforms/_list.wfl"
nameBuffer =  Sin

nameBuffer =  Square

nameBuffer =  Triangle

nameBuffer =  Sawtooth

nameBuffer =  DC
newName =  "Sin"
opening "/Volumes/bin:Labrador/Labrador.app/Contents/MacOS/waveforms/Sin.tlw"
Length =  128
Divisibility =  4
List loaded!!
Making USB Driver invisible!!
pipeID 0 = 129
Generic Usb Driver setup complete
unixUsbDriver created!
driver =  unixUsbDriver(0x7fc27669d000)
axes =  QCustomPlot(0x7fc276110c20, name="scopeAxes")

**Comment by EspoTek** [comment]
Are you running 10.16 (Big Sur)?

**Comment by hchaudh2** [comment]
It is Big Sur version 11.2.1

**Comment by EspoTek** [comment]
Sorry, I'm an idiot!  I read it as 10.11 (El Cap).
Just enter the line `export QT_MAC_WANTS_LAYER=1` before launching from terminal and it should work perfectly.

**Comment by hchaudh2** [comment]
Oh my god! It works! Thank you so much. I honestly really appreciate it a lot.

**Comment by EspoTek** [comment]
No worries.  Hope you enjoy!

**Comment by hchaudh2** [comment]
Sorry to bother you again, but when I click current on Multimeter, it says F for all values. Can you help me with this?

**Comment by EspoTek** [comment]
What is your series resistance set to?

**Comment by hchaudh2** [comment]
0 ohms

**Comment by hchaudh2** [comment]
It works when I change it to for example 47 ohms but I'm not getting the proper readings for voltage, current or resistance.

**Comment by EspoTek** [comment]
Check the docs.  They specify how to lay out a circuit for the multimeter, and what resistance ranges are sensible.
https://github.com/EspoTek/Labrador/wiki

Alternatively, get yourself an El Cheapo multimeter.  I still use my $10 Jaycar meter I got as a kid - they're simpler to use and very handy.
