### ISSUE TITLE
Driver is unavaiable

### ISSUE THREAD

**Issue by cthorsby** [EspoTek/Labrador#150]
I have tried restarting and updating my PC as well as using different cables. However, I keep getting the error message of the driver is unavailable.

**Comment by EspoTek** [comment]
Hi mate, can you please send a couple of screenshots showing what you mean?  I'm not familiar with that particular error message.

**Comment by cthorsby** [comment]
![Screenshot (167)](https://user-images.githubusercontent.com/79289814/109539834-bf1a0e80-7a8f-11eb-83be-7b38a8e7901c.png)
![Screenshot (169)](https://user-images.githubusercontent.com/79289814/109539853-c3dec280-7a8f-11eb-9477-e5ca9c3b14cd.png)

![Screenshot (172)](https://user-images.githubusercontent.com/79289814/109539868-c80ae000-7a8f-11eb-8f97-0057ae6c2776.png)

**Comment by EspoTek** [comment]
Did you solve the problem?
