### ISSUE TITLE
Pull data from multiple boards to have more channels to work with... Possible?

### ISSUE THREAD

**Issue by MrMaint** [EspoTek/Labrador#154]
I was looking at the Raspberry Pi shield that has 10 channels, but not as many other impressive features as the Labrador,  and wondered if the software could pull data from multiple Labrador boards to gain the use of 4, 6, or 8 channels. Would it be possible for the software to automatically recognize additional boards and show and coordinate more channels?

**Comment by EspoTek** [comment]
This is definitely technically possible, but it's quite a niche use case and would be a significant undertaking to get up and running.  For those reasons, it's not something that I plan on implementing.

**Comment by techdragon** [comment]
@EspoTek does this mean the software can't work with more than one Labrador board?

**Comment by EspoTek** [comment]
It means that it's technically possible, but you'd need to rewrite the software to do it.
You can only run a single instance of the official software, and you can only connect it to a single board.

**Comment by techdragon** [comment]
@EspoTek Thanks for the reply! Not a lot of maintainers ever seem to notice comments on closed issues.
