### ISSUE TITLE
help measuring current in multimeter mode

### ISSUE THREAD

**Issue by khtodd1** [EspoTek/Labrador#157]
Hello.  I'm trying to use Labrador to measure the gate current when switching on a MOSFET from an output of a microcontroller.  I've read the Wiki 500 times but I'm not still not quite sure how to connect it to measure what I want.  Can you please explain, or even better, throw up a quick circuit sketch?  Thank you.

**Comment by EspoTek** [comment]
Unfortunately, I don't think it's a simple task for a device such as this to measure MOSFET gate currents as they're likely to be in the nA range.
However, if you could, the circuit diagram would like like this:
![IMG_8859](https://user-images.githubusercontent.com/22040436/111422374-b3427380-8742-11eb-9471-5c4e0f4ebf88.JPG)
A load resistor is placed in series with the current you want to measure, and the two channels of the scope are added across the load.

The software interface looks like this:
<img width="770" alt="Untitled" src="https://user-images.githubusercontent.com/22040436/111422443-d3723280-8742-11eb-9d94-0e8e1c83b8df.png">
Set the multimeter mode to "I" and manually enter the value of the series resistance (load resistor from circuit diagram) into the box shown.

Sorry if I can't be of more help.  If you're really keen to measure something that small, maybe consider looking to the uCurrent or similar?

**Comment by khtodd1** [comment]
Thank you for your help with this - it's a power MOSFET - so the gate
current could actually get up to 100mA or so, although I'd like to see it
on the order of 10-15mA.  I will try your suggestion.

**Comment by EspoTek** [comment]
Ahh, of course.  You should have no issue then.
