### ISSUE TITLE
Feature: frequency display

### ISSUE THREAD

**Issue by waseltzer** [EspoTek/Labrador#159]
It would be useful to be able to display frequency in the oscilloscope mode all the time for periodic signals.
With the current features, need to drag a vertical cursor to measure a time interval and manually repeat this when the frequency of the signal changes.

One way to do this is to use the time between 2 trigger points.

(This is a common feature on other oscilloscopes.)

**Comment by EspoTek** [comment]
![image](https://user-images.githubusercontent.com/22040436/123248537-633a3080-d52b-11eb-8170-c2e32e836614.png)

Just added this in!  Thanks for the suggestion.
