### ISSUE TITLE
QT dll(s) missing

### ISSUE THREAD

**Issue by khatharr** [EspoTek/Labrador#163]
Win 8.1 x64, after installing I try to run the software and get this:

![ss+(2021-03-22+at+05 43 52)](https://user-images.githubusercontent.com/11417920/112075802-6e4d8100-8b36-11eb-882a-56f3eaf821f2.png)

**Comment by EspoTek** [comment]
My apologies.  Looks like the dependency was stealth-added in a recent patch.
Build 269 and onwards should no longer have this issue.  I'll delete the old ones to prevent accidental installs!
