### ISSUE TITLE
labrador software not working on mac

### ISSUE THREAD

**Issue by hchaudh2** [EspoTek/Labrador#168]
I've been trying export QT_MAC_WANTS_LAYER=1  to open the labrador software, but it isn't working. It was working fine last week, but now it says: “Labrador” cannot be opened because the developer cannot be verified. macOS cannot verify that this app is free from malware.

Do you have any solutions for this?

**Comment by EspoTek** [comment]
It's unsigned.  You'll need to right-click then open rather than double clicking.  On Catalina and later, you may also need to drag it into /Applications as well (I'm, still not 100% sure about this one).

**Comment by lkoepsel** [comment]
I've been using the Labrador on macOS for quite some time. It works on both Catalina and Big Sur. As of the release in early March (approx), no additional commands are required to use the Labrador application on Big Sur.

A little more detail as to Chris' comments:
1. Download the latest release .dmg file.
2. Double-click it to mount it in Finder then drag to the Applications folder
<img width="1648" alt="Finder" src="https://user-images.githubusercontent.com/7906684/113483500-9bfcc900-9458-11eb-863b-dfa20a569a04.png">
3. Right click on the file and select Open.
<img width="697" alt="Rightclick" src="https://user-images.githubusercontent.com/7906684/113483529-c5b5f000-9458-11eb-9a93-f93b2c3173b7.png">
4. The first dialog screen doesn't show the option to Open the file. Close the first screen, then do the same thing again. This dialog screen will allow you to open it.
<img width="557" alt="Second Right Click" src="https://user-images.githubusercontent.com/7906684/113483566-f138da80-9458-11eb-9ccc-2e785e6d2d0f.png">
5. You know you are successful when you see this screen:
<img width="478" alt="Calibration Required" src="https://user-images.githubusercontent.com/7906684/113483577-0150ba00-9459-11eb-90a6-638f1f04b35f.png">

I've got additional notes on the Labrador on my site: www.wellys.com
