### ISSUE TITLE
External Scope probes?

### ISSUE THREAD

**Issue by kevinpowell** [EspoTek/Labrador#173]
Breadboard mounting is fine, but I'm more likely to put the Labrador in a small enclosure and wire up a couple bnc connectors for a traditional scope probe.  Would there be any issues doing this?  Will a standard tektronix (1x and 10x) probe work well?

**Comment by EspoTek** [comment]
Hi Kevin, you'll have absolutely no issues with this.  It's quite common for people to do this, and there are even 3D printable enclosures on Thingiverse with holes for BNC probes.

Good luck with the projects, and feel free to send pics when you're done.  Always like seeing what people get up to!
