### ISSUE TITLE
Feature Request: Low Pass filter

### ISSUE THREAD

**Issue by kevinpowell** [EspoTek/Labrador#174]
I've been using the Labrador for tuning servo motors in CNC applications -- it is much more convenient than my old bench scope.  However, the output from e.g. tachometer sensors is quite noisy; lots of high-frequency artifacts.  One feature that I miss from my bench scope is the ability to low-pass filter the input signal.  Any chance of having such a filter added to the labrador software?  It should be relatively easy to apply a filter on the PC/USB host side.

**Comment by EspoTek** [comment]
Old beta versions of the software had an optional moving average filter.  I ended up removing it from the release version of the software because it didn't gel properly with the UI and I also didn't like how it made my signals look "too clean".  Maybe it's time to reconsider that decision...
