### ISSUE TITLE
Windows software entering firmware flash after psu error

### ISSUE THREAD

**Issue by Alattice** [EspoTek/Labrador#178]
I believe there's 2 issues here: one involving the psu and another in software.

The psu seems to be unable to reach above 11v:
Sliding the psu to ~11v in software (2201ada), causes the output to drop back down to ~4.77v. the capacitor by the logic analyzer pins get warm along with the chip itself. The software then enters a state where it'll animate the last waveform recorded and say it's connected to the board, even after I unplug it.

After plugging it in again the software doesn't change. Upon rebooting the program, it will always enter firmware flashing mode regardless of whether the board is present.

Restarting my computer fixes the problem, but every time I perform the action with the psu the same thing occurs.

**Comment by EspoTek** [comment]
Hi mate.  The behaviour that you described is exactly what you'd expect from an out-of-spec board.  Long story short, the current draw at 12V trips the OCP and the board shuts down.

Please contact me at admin@espotek.com for a replacement.
