### ISSUE TITLE
What is Vcc for the Labrador?

### ISSUE THREAD

**Issue by mistere357** [EspoTek/Labrador#179]
I'm looking for Vcc info for the Labrador board ( Min - Nominal - Max) 
I've read through the documentation so if it's there I just missed it :frowning: 
A nominal 5.0 V DC makes sense however as a source it can output 12 V DC.  Boost converter?
Thank you

**Comment by EspoTek** [comment]
I'm not quite sure what you mean by this question.  You should not be supplying any additional power to the board other than the USB input.

**Comment by mistere357** [comment]
There are two pins that plug into the COM and + rows of the breadboard. 
If I don't have to do anything with them that's great. 
Thank you

**Comment by EspoTek** [comment]
They're output pins, not inputs!  No additional hardware required.

**Comment by mistere357** [comment]
Yes, as soon as you said all I needed was the USB I understood! :bulb: 
Great product by the way - I'm having fun tinkering with it. 
I bought 2 so I'm going to set up the 2nd one on my laptop (1st is on the Raspberry Pi) and use the outputs from one as input to the other :grin: 
Thank you again!

**Comment by EspoTek** [comment]
Awesome, hope you enjoy!
