### ISSUE TITLE
Could you please update the Windows binary?

### ISSUE THREAD

**Issue by aalku** [EspoTek/Labrador#18]
Could you please update the Windows binary?
I tried to compile it myself but I was unable to do it :(

**Comment by EspoTek** [comment]
Understandable.  I'll add a "release" as soon as possible (probably within 24 hours).

**Comment by EspoTek** [comment]
Looks like I found time to put together an installer.  Check the releases page in a few minutes and there'll be a binary file there for you.

https://github.com/EspoTek/Labrador/releases

**Comment by aalku** [comment]
Thank you!
