### ISSUE TITLE
Feature request: Generate PWM signal using the onboard signal generator

### ISSUE THREAD

**Issue by gshiva** [EspoTek/Labrador#182]
Will be very useful to test motors. Ideally it would be a software update where the parameters can be tuned, a document update would also work.

**Comment by EspoTek** [comment]
Currently there are no plans to add anything like this to the software, but you can custom-define your own waveforms according to this guide:
https://github.com/EspoTek/Labrador/wiki/Defining-a-Custom-Waveform
