### ISSUE TITLE
What should I do after replace a new ATXMEGA32A4U-AU chip on labrador?

### ISSUE THREAD

**Issue by littlepotato999** [EspoTek/Labrador#184]
I just burned the orginal mcu chip on board and replace the bad one with a new ATXMEGA32A4U-AU, but when I plug in, I just can't use any features the labrador has, I think it's because the mcu is new, and what should I do to solve this issue? 

Thanks,

**Comment by EspoTek** [comment]
Hi mate.  Was this closed by mistake?  You'll need to reprogram the chip using an Atmel PDI Programmer.  If you email me at admin@espotek.com, I can pass on the same programming files the factory uses as well as instructions on how to do this in Atmel Studio (free).
