### ISSUE TITLE
What should I do after replacing the MCU chip on labrador with a new ATXMEGA32A4U-AU?

### ISSUE THREAD

**Issue by littlepotato999** [EspoTek/Labrador#185]
I just burned the orginal mcu chip on board and replace the bad one with a new ATXMEGA32A4U-AU, but when I plug in, I just can't use any features the labrador has, I think it's because the mcu is new, and what should I do to solve this issue? 

Thanks,

**Comment by EspoTek** [comment]
Looks like this is a duplicate.  Please email me at admin@espotek.com and I'll pass on the factory files for you.
