### ISSUE TITLE
Error with Continuous build (macOS)

### ISSUE THREAD

**Issue by feiltom** [EspoTek/Labrador#186]
Hello, 
I think the last Continuous build (macOS) is in error. ( 2mo before 78mo )
I Can use the last Dmg on my MacOs 10.15

**Comment by EspoTek** [comment]
Hi mate.  I can't see any problems on my machine.  Please can you tell me exactly what error you see?

**Comment by tomhougaz** [comment]
Same error here on macOS Catalina 10.15: You can't open the application "Labrador" because it may be damaged or incomplete.
I tried xattr -cr but does not solve the issue. Same error when trying with another macbook with Catalina.  DMG size: 2.2 MB. And app size: 4.6MB

**Comment by EspoTek** [comment]
Looking at the build history, it seems like it's been pushing code from the Pull Request to the main release!
I've added a fix for this and the DMG should be fixed as soon as the current build completes.

**Comment by EspoTek** [comment]
Yep, looks like the build has been fixed.  Sorry about that interruption!

**Comment by feiltom** [comment]
Perfect !
