### ISSUE TITLE
Device not connected on 3 different systems

### ISSUE THREAD

**Issue by pmpbar** [EspoTek/Labrador#19]
Hello! The desktop software is not picking up my Labrador in macOS, Debian linux and also Windows 8.1. I can see an Atmel Corperation usb vendor ID when I check but the oscilloscope software will not pick it up. The linux system was a virtualbox but the windows and Mac systems were real computers. Is there some trick to getting the little guy to get picked up? I tried switching around to all the ports on the machines to see if that would help. Let me know what info is needed to help.

**Comment by EspoTek** [comment]
Sounds like something went wrong with the firmware updating process.

Plug in the board on Windows, navigate to the /firmware directory of your installation and run 'flash.bat'.

Faster and more stable firmware flashing is something that will be in the next few updates.  It's already implemented in Windows (source only ATM), just need to copy and paste a bit of code to get it running on Linux/Mac/Android.

**Comment by EspoTek** [comment]
Also note that it will reflash the firmware whenever you switch between Windows x64 and other platforms.  This is to help overcome bandwidth limitations on Windows.

Make sure you don't unplug the board during this flashing stage (approx 10 seconds).

**Comment by pmpbar** [comment]
I am getting a device not found when I run the flash script. Maybe my board is bunk?

**Comment by EspoTek** [comment]
You said you got an Atmel VID...  What's the PID?

**Comment by EspoTek** [comment]
Or, on Windows, what does device manager say?

**Comment by pmpbar** [comment]
Sorry for the delayed response, the PID is ba94. `ID 03eb:ba94 Atmel Corp.`

**Comment by EspoTek** [comment]
Yep, that's the correct VID/PID.  I suspect it's just clashing with another device.  Unplug all other devices connected to USB2.0 ports and connect Labrador through the 2.0 port.  If you connect it though a hub, ensure that it's the only device on the hub.  If you have a spare hub, connect  only the Labrador to the hub, and plug on through the hub.  That should fix it.  Long story short, it's a quirk of Atmel's USB controller when dealing with isochronous connections, mixed with the way that most USB devices handle 12mbps devices.

The troubleshooting section of the documentation has a short explanation and a few tips.

**Comment by pmpbar** [comment]
Hmm, I have it directly connected. I will mess around with it more and see what I can learn.

**Comment by EspoTek** [comment]
Interesting.  No keyboard or mouse on the bus?

Does the cable you're connecting it through support data as well as power?  Some cheap ones don't.  Try connecting a phone to the PC and see if you can transfer data.

**Comment by EspoTek** [comment]
The red light will come on even if there's no data line, by the way.  It just means that the power supply is active.

**Comment by EspoTek** [comment]
Did you end up getting it working?

**Comment by saudalwasly** [comment]
I have the same problem with Linux. I do not have a Windows machine. Is there any way to connect to the board?
What driver are you relying on?

**Comment by EspoTek** [comment]
If you have Linux, could I please ask you to send me output of `lsusb` both when the board is disconnected and when it's connected?

No driver is required on Linux.

**Comment by saudalwasly** [comment]
I have got it working now by pluging it in a USB2 port. For some reason it
doesn't work with USB3 port!

Is there any explanation?

**Comment by EspoTek** [comment]
>Is there any explanation?

Yes, it was most likely bandwidth limitations:
https://github.com/EspoTek/Labrador/wiki/Troubleshooting-Guide

I'm guessing there was a webcam or other device plugged into one of your USB3 ports.

**Comment by EricShalov** [comment]
Having the same problem, on MacOS 14.5 on a 2.6GHz MBP. I plug it in using a known-good not-only-power cable, it then appears on the bus when I run 'ioreg -p IOUSB', as this:
    	  | +-o IOUSBHostDevice@14200000  <class AppleUSBDevice, id 0x1008246b6, registered, matched, active, busy 0 (1 ms), retain 14>

..but when I run the Labrador MacOS/X app, it just says "Device Not Connected!"

**Comment by EspoTek** [comment]
> Having the same problem, on MacOS 14.5 on a 2.6GHz MBP. I plug it in using a known-good not-only-power cable, it then appears on the bus when I run 'ioreg -p IOUSB', as this: | +-o IOUSBHostDevice@14200000 <class AppleUSBDevice, id 0x1008246b6, registered, matched, active, busy 0 (1 ms), retain 14>
> 
> ..but when I run the Labrador MacOS/X app, it just says "Device Not Connected!"

What does `lsusb` show when the board is connected (you can install lsusb through homebrew)

**Comment by taybart** [comment]
>What does lsusb show when the board is connected (you can install lsusb through homebrew)

On macos you can also use `system_profiler SPUSBDataType`
