### ISSUE TITLE
fail to install on the new raspberry pi OS Bullseye 

### ISSUE THREAD

**Issue by Ethanali** [EspoTek/Labrador#197]
can't get qt5-default

**Comment by EspoTek** [comment]
Thanks.  I'll look into this when I have the time.

A quick google suggests the following should function as a workaround:
`sudo apt-get install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools`

~Chris

**Comment by jsmittelman** [comment]
> Thanks. I'll look into this when I have the time.
> 
> A quick google suggests the following should function as a workaround: `sudo apt-get install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools`
> 
> ~Chris

tried that, still cannot locate qt5-default

**Comment by EspoTek** [comment]
You don't need qt5-default.  Just remove the line from the script.

**Comment by EspoTek** [comment]
This is now fixed.  The updated script has been tested on both Stretch and Bullseye.
