### ISSUE TITLE
Add Qt project files

### ISSUE THREAD

**Issue by Prince-of-Persia** [EspoTek/Labrador#2]
Please add Qt project files so it's easier for other developers!

**Comment by EspoTek** [comment]
Sorry for taking so long to respond; I just saw this issue now!
The project files have been included from day 1.  Look for Software Interface/labrador.pro.
This project file is compatible with all platforms.
Make sure to follow the build instructions here:
https://docs.google.com/document/d/1ZDO1RTarQTNB6Pdfi_T4YukL51oYan_kk_teb1cu6-o/edit?usp=sharing 

Note that in past (Windows-only) revisions it was called Labrador_libsubk.pro.
