### ISSUE TITLE
Some values are not labelled

### ISSUE THREAD

**Issue by benlhy** [EspoTek/Labrador#20]
I was looking at your design and I saw that some values are not labelled. For example the inductors are only labelled as 'SMD Inductor'.

**Comment by EspoTek** [comment]
Oh, you're right!
The SMD Inductors are 10uH for the 1206ers, and 100uH for the self-wound.

I'm not sure which resistor is which, but can have a look.
Do you mind submitting a pull request for them?

**Comment by kasbah** [comment]
Yes, all the capacitors are missing values int the schematic too.
