### ISSUE TITLE
Device Descriptor Request Failed

### ISSUE THREAD

**Issue by beingkailo** [EspoTek/Labrador#203]
Win 10 PC. I installed the drivers and software. I plugged a USB cable into the Labrador board, the red light on the board came on and I got this message:
Device Descriptor Request Failed
Windows does not know what kind of device it is. I assume that means that the usb cable is a data cable. Is the board failing in its handshake with the PC?
Thanks

**Comment by EspoTek** [comment]
>Is the board failing in its handshake with the PC
Yep, that's 100% correct.  All USB devices go through an initial handshake process called "enumeration" to identify what they are, and it looks like this failed.

If it's not the cable, it's almost certainly indicative of some sort of hardware failure.

Please contact me at admin@espotek.com and I'll organise a free replacement board for you.
