### ISSUE TITLE
Surfacing detailed documentation links

### ISSUE THREAD

**Issue by couchand** [EspoTek/Labrador#206]
Hello!  I've been having a good time digging into the Labrador.  Nice board, thanks for all your hard work!

Two pieces of documentation have been invaluable for me, but I only found them by digging through old issues:

- [Labrador Developer Documentation](https://docs.google.com/document/d/1ZDO1RTarQTNB6Pdfi_T4YukL51oYan_kk_teb1cu6-o/edit)
- [Librador User Guide](https://docs.google.com/document/d/11Cu6602X_y5x0IwIBZnP7ImIx0jykX7AzToh83-7hCM/edit)

This brings up two questions in my mind:

- Are there any other juicy bits of documentation hidden away in Google Docs?
- What would be the right place to surface links to these documents?  Perhaps a page on the Wiki?

Point me in the right direction and I'd be happy to write something up on the wiki or elsewhere.

**Comment by EspoTek** [comment]
> I've been having a good time digging into the Labrador

My God, you have been busy!

I honestly can't think of anything else that's of public interest, but if you're super curious about the project I did manage to find an old report from back when I was a student (amongst some other random crap):
https://docs.google.com/document/d/1QiakPVND03OV0eQtuVhLd7T4j8-GkRSesFZ7BunJpcg/edit?usp=sharing

(Is it just me that wants to know absolutely every single minute detail of a new interesting thing?)

I've added a "Further Reading" section to the Wiki.  Feel free to make any edits you'd like to it!
https://github.com/EspoTek/Labrador/wiki/%F0%9D%96%A5urther-Reading
