### ISSUE TITLE
Power by switch - QUESTION

### ISSUE THREAD

**Issue by bpod** [EspoTek/Labrador#207]
Does anyone have advice on how I would wire the power up to a switch to easily turn the board on/off?

Thanks in advance.

**Comment by EspoTek** [comment]
You could quite easily wire a switch into the +5V rail adjacent to the USB connector, but I'm honestly not quite sure why you'd want to.  Is there a reason you can't just unplug the board after use?

**Comment by bpod** [comment]
Nope.. Was mainly just curious. Was thinking of building a case that is always plugged in. With leads, switches, etc.

**Comment by EspoTek** [comment]
Ahh, gotcha!  That makes sense, thinking about it.  Let us know how you go if/when you get it working.  Just cut the +5V trace with a screwdriver or dremel, expose some copper on either side of the break and wire in the switch.  Classic bodge work!
