### ISSUE TITLE
failure to  calibrate

### ISSUE THREAD

**Issue by davesnake3** [EspoTek/Labrador#208]
I have two Labrador boards and have installed on two different computers. I have tried all USB ports. When I try to calibrate calibration fails "Calibration has been abandoned due to out-of-range values". I have uninstalled and reinstalled software 3 times. The boards show they are connected the computer recognizes the boards when connected (one at a time). Help,  Pllease

**Comment by EspoTek** [comment]
Yep, this is a known issue.  Patch coming soon!

**Comment by EspoTek** [comment]
Patch uploaded.  Please let me know if that didn't fix the problem.
