### ISSUE TITLE
Getting pins into the breadboard

### ISSUE THREAD

**Issue by johnchurchill** [EspoTek/Labrador#209]
Before I risk damaging my brand new Labrador, can someone advise if the attached picture is normal and I should be bending the PSU pins so far to get into the power rail? My board says "Batch 2" if that matters.

![labrador](https://user-images.githubusercontent.com/2926598/151276910-a7614282-ade8-4533-a840-871d7c6eb50a.jpg)

**Comment by EspoTek** [comment]
Yep, it's fine.  The measurements are slightly off on some breadboards.

**Comment by jimustafa** [comment]
I have a "Batch 2" board as well; but, in my case, the power supply pins appear to be missing. Is there something wrong with the board?

![image2](https://user-images.githubusercontent.com/4108888/164836465-f75bb644-0d39-408f-999d-5bd11ae378be.jpeg)
![image3](https://user-images.githubusercontent.com/4108888/164836470-db5bad93-d6aa-4cb8-9137-23f55ffbe3da.jpeg)

**Comment by EspoTek** [comment]
That is a manufacturing error.
Please contact me at admin@espotek.com and I'll organise a replacement for you.
