### ISSUE TITLE
Espo tek Labrador Software installation failure

### ISSUE THREAD

**Issue by nelkhal10** [EspoTek/Labrador#216]
Hi,

I’m trying to get up running with the EspoTek Labrador, but I’m not able to install the software correctly. I’m getting failure when installing Espotek Labrador Driver (Primary) and the Espotek Labrador Driver (Misconfigured Batch Feb 2020), see screenshots in attachment.

My OS (64 bits) is : Windows 10 Entreprise version 20H2. My firewall was disabled during installation.
Thanks for your help.

![Espo Tek Labrador-Capture1](https://user-images.githubusercontent.com/102309289/159948909-8f6652d3-f8bc-476f-a7f4-4dc5d6f932c9.PNG)
![Espo Tek Labrador-Capture2](https://user-images.githubusercontent.com/102309289/159948910-0c2d6447-09a3-44f9-ae79-7c2a76b59dc0.PNG)
![Espo Tek Labrador-Capture3](https://user-images.githubusercontent.com/102309289/159948911-51acde6c-59db-4174-b18e-e1a1c6407118.PNG)
![Espo Tek Labrador-Capture4](https://user-images.githubusercontent.com/102309289/159948913-a94ba4b0-e242-4efd-a317-3827b36c7d33.PNG)

**Comment by EspoTek** [comment]
Hi Nancy.  Received your email too.

Copying reply here in case someone else is having this issue, but it's almost certainly an issue with the way your IT have configured your Enterprise install.

```
Hi Nancy.

It looks like your IT guys have disabled certain types of driver install.
You should be able to install it manually through Zadig, though.

To do this, please download Zadig from the following link:
https://zadig.akeo.ie/

Then perform the following steps:
 - Open the Zadig software
 - Select "Options" from the top menu, then "List All Devices" (Step 1 in picture)
 - From the drop-down menu, select Labrador (Step 2 in picture)
 - In the spinbox, change the driver to libusbK (Step 3 in picture)
 - Press the "Upgrade Driver" button.  (Step 4 in picture)

Note that the button may also say "Replace Driver", "Install Driver" or something similar.  Press it anyway.  :)
Also note that your software might not look exactly the same as the screenshots, as I already have the driver installed.

If that doesn't work, you'll need to talk with IT as it means they've explicitly disabled something.  Mention the steps you've taken with Zadig; they should be familiar with that software but probably aren't familiar with Labrador.  :)

Cheers,
~Chris
```
<img width="452" alt="Diagram" src="https://user-images.githubusercontent.com/22040436/160025986-52ce44b1-adbe-474c-bcb6-f501ebfec7a2.png">
