### ISSUE TITLE
ESPOTEK Labrador:  "Last usb device you connected to has malfunctioned and Windows does not recognize it"

### ISSUE THREAD

**Issue by miked9746** [EspoTek/Labrador#221]
That is the message I get after about 6-8sec of Windows trying to communicate with the board.  I've tried every troubleshooting trick I could find online, I've unplugged/plugged it in 600x, I've used every USB port that's available, unplugged every other USB device multiple times, uninstalled/installed several times, and yes...   my micro USB cord can transfer data.    I've tried to run the Flash, but the C: window just flashes on the screen for a microsecond, then nothing...
   It's clearly the device itself.
![20220511_011933](https://user-images.githubusercontent.com/105345924/167793842-20f8fcac-ab65-4c2c-a38d-9d77e3fd9437.jpg)

**Comment by EspoTek** [comment]
Yep, if your microUSB cable works with other devices, then it's definitely a manufacturing fault!

Please contact me at admin@espotek.com and I'll sort you out with a free replacement.
