### ISSUE TITLE
Segmentation fault at exit

### ISSUE THREAD

**Issue by jfbauer432** [EspoTek/Labrador#223]
Not a big deal, but when running EspoTek_Labrador-2cc0678-x86_64.AppImage on Linux (Ubuntu 21.04) it will crash with a segmentation fault when quitting the program: either closing the window, or choosing File->Quit

Running in gdb, I get...

> Thread 1 "Labrador" received signal SIGSEGV, Segmentation fault.
> 0x0000000000400080 in ?? ()
> (gdb) bt
> #0  0x0000000000400080 in ?? ()
> #1  0x00007ffff6d0150f in QBoxLayout::~QBoxLayout() ()
>    from /tmp/.mount_EspoTek5icXb/usr/bin/../lib/libQt5Widgets.so.5
> #2  0x00007ffff6d01599 in QHBoxLayout::~QHBoxLayout() ()
>    from /tmp/.mount_EspoTek5icXb/usr/bin/../lib/libQt5Widgets.so.5
> #3  0x00007ffff6d266c8 in QWidget::~QWidget() ()
>    from /tmp/.mount_EspoTek5icXb/usr/bin/../lib/libQt5Widgets.so.5
> #4  0x00007ffff6d26ae9 in QWidget::~QWidget() ()
>    from /tmp/.mount_EspoTek5icXb/usr/bin/../lib/libQt5Widgets.so.5
> #5  0x00007ffff622f483 in QObjectPrivate::deleteChildren() ()
>    from /tmp/.mount_EspoTek5icXb/usr/bin/../lib/libQt5Core.so.5
> #6  0x00007ffff6d268ed in QWidget::~QWidget() ()
>    from /tmp/.mount_EspoTek5icXb/usr/bin/../lib/libQt5Widgets.so.5
> #7  0x00007ffff6d26ae9 in QWidget::~QWidget() ()
>    from /tmp/.mount_EspoTek5icXb/usr/bin/../lib/libQt5Widgets.so.5
> #8  0x00007ffff622f483 in QObjectPrivate::deleteChildren() ()
>    from /tmp/.mount_EspoTek5icXb/usr/bin/../lib/libQt5Core.so.5
> #9  0x00007ffff6d268ed in QWidget::~QWidget() ()
>    from /tmp/.mount_EspoTek5icXb/usr/bin/../lib/libQt5Widgets.so.5
> #10 0x00000000004b2912 in ?? ()
> #11 0x00000000004b09d2 in main ()
>

**Comment by EspoTek** [comment]
Yeah, since this doesn't affect the functionality or performance of the software, I'll just leave it as is.
