### ISSUE TITLE
Device will only measure 3 volts

### ISSUE THREAD

**Issue by JvilleJTW** [EspoTek/Labrador#226]
Trying to test my Labrador. Comparing it against my DMM on a simple circuit with an LED and resistor driven by a lab supply of 9 volts DC. DMM correctly shows 7.6 volts across resistor. Labrador in Multimeter mode shows 3V consistently. Using CH1, CH2 and Gnd. terminals hooked up to test leads. I have tried increasing voltage headroom, but this appears to only affect the onboard voltage supply. Neither DC scope channel makes any sense either. Using a Mac laptop.

**Comment by EspoTek** [comment]
Hi mate.  This isn't so much as a bug as questionable UI design.  Zoom out the scope trace so that the analog waveform is visible at 7.6V, and the digital display should start updating with the correct values too.

**Comment by JvilleJTW** [comment]
Chris--

This makes no sense. Neither the multimeter nor the scope are reading the correct figures. It's not close; they are off by 4-5 volts. I am abandoning this project.

JTW
