### ISSUE TITLE
Desktop_Interface build

### ISSUE THREAD

**Issue by dbsamithey** [EspoTek/Labrador#238]
I think that these steps need to be taken to build the application on MacOSx
- a qt5 version of qmake should be used (Qt5.15.8 worked for me)
- 'macx: INCLUDEPATH += /usr/local/include' may need to be commented out in Labrador.pro to prevent the compiler from finding Qt6 code in /include
- as a brute-force fix to the program not being able to find libdfuprog-0.9.dylib, it can be copied from /build_mac to /Labrador.app/Contents/MacOS
- similarly, /waveforms from /Labrador.app can be copied to /Labrador.app/Contents/MacOS

**Comment by EspoTek** [comment]
Thanks for that.  I'll add it to the main page now.

See also the build script here:
https://github.com/EspoTek/Labrador/blob/master/.travis.yml
