### ISSUE TITLE
32-bit windows fails: can't find msvcp140.dll

### ISSUE THREAD

**Issue by BenGardiner** [EspoTek/Labrador#24]
issue occured on most recent release downloaded here from github

easy enough to fix by installing https://www.microsoft.com/en-us/download/details.aspx?id=53840

**Comment by EspoTek** [comment]
Thanks for letting me know.  The package includes Visual C++ 2013 redistributable, but it looks like I compiled with 2015 by mistake.  I'll fix that in the next revision.

**Comment by EspoTek** [comment]
I've edited the release page to Windows 32-bit users with DLL issues to your issue.
Bug will be fixed in the next release, as mentioned before.

Thanks.  :)
