### ISSUE TITLE
Device not Detected Windows 

### ISSUE THREAD

**Issue by hjrjacquez** [EspoTek/Labrador#247]
Good day,

I was working on a project and midway through it the software stopped recognizing the board but the light still turns on. My laptop runs on Windows 10, it's a Lenovo Ideapad.
I tried the following:
Restarting the computer,
Getting a new cable (It's one that can transfer data)
Uninstalling and reinstalling,
Tried looking for the device in the device manager as stated in the guide but no go.
Tried on another laptop with a fresh install and still did not recognize the board.

When I plug the debug console I get the following:
![debug](https://user-images.githubusercontent.com/132848916/236699711-1a62fbc6-1395-4567-955f-7bc16534c084.PNG)

Does anyone know how to solve this?

**Comment by EspoTek** [comment]
It sounds like the board popped while you were working on your project.

Could the voltage have spiked above 20V on any of the pins?  Did you smell any magic blue smoke when it stopped working?

**Comment by hjrjacquez** [comment]
Thank you so much for your response. I was working with 5V. No smell or smoke came from it. Is there any way I can test if it popped? This is the last time it worked, I was making this measurement. 
![IMG_20230507_040316380](https://user-images.githubusercontent.com/132848916/236710371-7cf167ed-44fb-44e5-b6ec-21032a71c055.jpg)

**Comment by EspoTek** [comment]
Weird.  Please contact me at admin@espotek.com and I'll organise a free replacement for you.

If you're not getting any "USB Connected" noise at all, the board is cooked an there's nothing you can do.

Cheers,
~Chris
