### ISSUE TITLE
Curve tracer 

### ISSUE THREAD

**Issue by david0rk** [EspoTek/Labrador#250]
Between Power supply and signal gen it feels like it would be possible to get the labrador to function as a curve tracer.

**Comment by david0rk** [comment]
Thinking on it I was worried maybe buffers could be an issue, but instead of measuring across channels you'd be measuring against the known output from the signal gen on a single channel.  This may be doable.

**Comment by EspoTek** [comment]
I agree it would be doable, but it would be a lot of effort to implement and probably wouldn't be all that useful given the lack of precision on the device.
