### ISSUE TITLE
Device not detected!

### ISSUE THREAD

**Issue by MadJalapeno** [EspoTek/Labrador#252]
Just received my Labrador today.

Downloaded latest release from here, and installed drivers, etc. , but when I plug it into my computer nothing shows up in Device Manager, and the software shows a red "Device Not Connected!"

Have rebooted, and reinstalled, with no difference. I know the USB cable is good as I use it programming ESP32's but have tried a few just to be sure, as well as different USB ports.
```

DEBUG MODE ACTIVE
CHECKING CONNECTION!
Could not find device VID = 03EB, PID = BA94
Connected
Could not find device VID = 03EB, PID = A000
CHECKING CONNECTION!
Could not find device VID = 03EB, PID = BA94
```
Any suggestions?

**Comment by EspoTek** [comment]
HI mate.  If it's not the cable, it's often a manufacturing defect.  Please send me an email at admin@espotek.com with any order info you have, as well as whether or not you have an AVR PDI programmer.
