### ISSUE TITLE
name space android studio 

### ISSUE THREAD

**Issue by shaynababe** [EspoTek/Labrador#254]
![Screenshot_2023-10-27_07-26-26](https://github.com/EspoTek/Labrador/assets/120763310/14a4444b-6156-4cad-bd11-bd5a15a4c753)
![Screenshot_2023-10-27_07-19-14](https://github.com/EspoTek/Labrador/assets/120763310/9306433d-923c-40e4-b0f2-f9f1053feeef)
agp upgrade to 8.1.2 fails
![Screenshot_2023-10-27_07-10-01](https://github.com/EspoTek/Labrador/assets/120763310/966e5745-2ffb-4450-a7fb-80f3df3cfaa0)
i have no idea what im doing 

the linux code will not build the android studio does

**Comment by shaynababe** [comment]
current qt 
![Screenshot_2023-10-27_09-54-19](https://github.com/EspoTek/Labrador/assets/120763310/32463dc2-6daa-4f8d-a67d-b504d4d042ab)

**Comment by EspoTek** [comment]
Yep, the Android code needs to be modified before it'll build.  There's a whole lot of magic stuff that's just been #defined out...

I'll look into patching it by the end of the year!
