### ISSUE TITLE
Howto manual firmware recovery?

### ISSUE THREAD

**Issue by brummer-simon** [EspoTek/Labrador#258]
Hi,

For some unknown reason my Labrador is stuck in the bootloader mode and I am not able to recover it.
I have used the firmware recovery function in the help menu and it says that the firmware is in bootloader mode but unable to recover the firmware. It would really help do document instruction on manual firmware recovery in the documentation, in cases there the automated mechanism fails. 

Are there instructions to flash the firmware manually?

Cheers and thanks.
Simon

**Comment by EspoTek** [comment]
I reckon I answer this question by email once every couple of weeks, yet never thought to add it to the Wiki...

Please see updated page here:  
https://github.com/EspoTek/Labrador/wiki/Troubleshooting-Guide

I'll close as "solved" for now, but if you have any other questions, feel free to post a response here!
