### ISSUE TITLE
Icon is not 256x256 pixels

### ISSUE THREAD

**Issue by probonopd** [EspoTek/Labrador#26]
Linux icons need to come in predetermined sizes such as 256x256 pixels if they are put into the standard locations such as `/usr/share/icons/hicolor/256x256/apps/`. Please provide a 256x256 pixels icon.

**Comment by EspoTek** [comment]
Fixed (finally!) in https://github.com/EspoTek/Labrador/commit/e8a817fe4d36be1fc7e88c363a4abbfeb10487d2
