### ISSUE TITLE
Desktop file lacks a main category

### ISSUE THREAD

**Issue by probonopd** [EspoTek/Labrador#27]
Value "Electronics;" for key "Categories" in group "Desktop Entry" does not contain a [registered main category](https://standards.freedesktop.org/menu-spec/latest/apa.html#main-category-registry); application might only show up in a "catch-all" section of the application menu.

Source: `desktop-file-validate`

**Comment by EspoTek** [comment]
Fixed (finally!) in https://github.com/EspoTek/Labrador/commit/e8a817fe4d36be1fc7e88c363a4abbfeb10487d2
