### ISSUE TITLE
"make install" does not work

### ISSUE THREAD

**Issue by probonopd** [EspoTek/Labrador#28]
`make install` does not work for Linux.

It is common on Unix to also use the build tool to install applications and libraries; for example, by invoking make install. For this reason, `qmake` has the concept of an install set, an object which contains instructions about the way a part of a project is to be installed.

Please see the section "Installing Files" on http://doc.qt.io/qt-5/qmake-advanced-usage.html.

**Comment by EspoTek** [comment]
Finally fixed this.
Installed Arch on a laptop and have been carrying it with me on the train to work.  I work as a software engineer now and am very rapidly learning how great the Unix command line is.  Don't know how I never noticed it over all these years.
