### ISSUE TITLE
Pinout - Still one discrepancy?

### ISSUE THREAD

**Issue by wavelet2** [EspoTek/Labrador#40]
There seems to still be one discrepancy between the (revised) pinout in the wiki documentation and the annotated photograph from the "Labrador Initial Documentation" document.
In the wiki pinout, the digital output next to the signal generator outputs is labelled "Digital Output 1" and that next to the gnd pin is labelled "Digital Output 4".
In the annotated photo, the 4 digital output labels are the other way round.
I suspect the photo is right and the wiki documentation wrong because I recently manually flashed the FW of my board by shorting the pin next to the signal generator outputs (labelled "Digital Output 4" in the _photo_) to gnd.

**Comment by EspoTek** [comment]
The new pinout is definitely correct; I just checked it in the Labrador software.

You're right in saying that the documentation refers to the old pinout diagram.  I'm in the process of updating it right now.

Thanks once again, it's amazing what you overlook when you're a one-man band.
