### ISSUE TITLE
DataLogger for Education

### ISSUE THREAD

**Issue by drtrigon** [EspoTek/Labrador#44]
As requested in #37 a new issue:

>> Another point here is; if the device would be a bit more fool-prove and the software a bit more intuitive to use (e.g. "beginner" mode) we could use it in schools for education (for teenagers, ~14yrs). Again all concurring products are about 10 times the price of a labrador. At least I would be immediately willing of ordering 10 to 20 devices for one school I am working at. :)
> 
> Drtigon, the hardware is actually designed to be foolproof. You can short any pin to any other pin and guarantee no damage. It's also difficult to break with external sources. You can hook up 18V directly to the signal generator, for example, and the only thing that will burn is one of "fuse" resistors which can be easily replaced with a blob of solder. Even if you can't solder, only the one output you damaged will become faulty; the rest will work OK.
> 
> Not really sure what I could do to make the software easier to use, but open to suggestions (please create a separate issue though)!

I am thinking of something like
* Vernier Logger Pro: https://www.vernier.com/products/software/lp/
* Vernier DataQuest™ Software for TI-Nspire™: https://www.vernier.com/platforms/texas-instruments/software/data-collection/dataquest/

Basically both have a play/stop button to start/stop capturing of data. The data is shown in a table (time series) and in an plot. Additionally the software has a database for sensors available to be able to have the correct ranges, units, etc. ready. This database could be something simple like an ini file.

> Send me an email at admin@espotek.com and I can get you a good deal on a class set, especially if you're happy to share educational materials you make. :)

This is the direction I am thinking of. ;))

**Comment by EspoTek** [comment]
Hey, sorry about the late response.  Have just been ridiculously overwhelmed at work.

The software idea looks pretty cool, but I don't have the time to develop it myself right now.  There's an API that just needs a bit of polishing up before release, though, and that could be used to make software like this.  Are you any good at programming?

Cheers,
~Chris

**Comment by drtrigon** [comment]
> Are you any good at programming?

I can solve issues by programming (python, c/c++) - but I would not talk about "how good I am"... ;) Would it be possible to release the API - even if it is not polished yet?

**Comment by EspoTek** [comment]
Of course.  It's been part of the main tree for a while.
https://github.com/EspoTek/Labrador/tree/master/Librador_API

Note that it's Linux-only for the moment.

**Comment by EspoTek** [comment]
Oh, and here's a full user guide.  
https://docs.google.com/document/d/11Cu6602X_y5x0IwIBZnP7ImIx0jykX7AzToh83-7hCM/edit?usp=sharing

It's basically public-beta ready.

**Comment by drtrigon** [comment]
Cool! Thanks a lot! Greetings

**Comment by EspoTek** [comment]
^^ Wow, that is a lot of ICs for a fairly similar device to the Labrador.  I think I've got two chips with more than 3 pins?

**Comment by drtrigon** [comment]
So let's do it better ... correct?

**Comment by EspoTek** [comment]
You mean a higher end Labrador 2.0?  If only I had the time!

**Comment by drtrigon** [comment]
Let's start and do it step-by-step. What's the first point? Specs and search for key parts?


Am 10. Februar 2019 00:39:33 MEZ schrieb Chris Esposito <notifications@github.com>:

**Comment by EspoTek** [comment]
Yep, that's the first step.  Important features are a High-speed USB 2.0 transceiver (not full-speed, which is annoying 1/40th the speed of high speed!), fast ADC, DMA and good documentation/support.
I remember reading about a MCU that had all of these features, but it cost around $7 per IC (compared to $2 for the Labrador 1.0's XMEGA32A4U).
Once I've picked a part I'd need to make sure that the software is basically plausible.
Next step would be to redesign the analog front-end.  6 resistors and half an LM324 won't cut it for higher frequency/bandwidth.  Finally, all of the software - both embedded and fixing the desktop software to get it to work with the new hardware.

Completely doable, but would be a massive investment of time which I would honestly rather put towards marketing Labrador 1.0 - at least for 2019.
It's a great product, but I only sell a few of them a week.  I think a big part of that is because I'm not getting out there and letting people know that it exists.  Both times it was reviewed in a magazine I sold 30-40 in the space of 2 weeks, and that was before the site redesign and eBay/Amazon listings (I was selling maybe 2-3 a week then, compared to 4-5 now).  More marketing materials (e.g. a demonstration video on the website) and some tutorials/educational materials would help a lot too.  \
At the end of the day, I'd honestly rather have 10,000 users with Labrador 1.0 than 2,000 users with Labrador 1.0 and another 2,000 users with Labrador 2.0.  Both in terms of business, and in terms of making a difference in electronics education, the more people that have access to hardware, the better.

**Comment by drtrigon** [comment]
Thanks for the insight!

> More marketing materials (e.g. a demonstration video on the website) and some tutorials/educational materials would help a lot too. 

Exactly what came to my mind... I am Physicist so let's brainstorm about that. With Labrador only, you can do power consumption measurement of e.g. a phone, a quadcopter, ... else?
For education or school some additional sensors might be needed.

Currently I work in a technical highscool that started a new program 3 years ago. My boss did and still does at least 1 visit for promo a week (for 3 years now). I also do some, why not for Labrador also? Good thing here in Switzerland the Labrador cost about the price of 3-4 boxes of cigarettes - so it's really affordable.

**Comment by ajxn** [comment]
My 2nd year Computer Engineering students have a project that could be to
design a prototype for a GUI in Java or something like that.
To bad it is in the winter, so that project course has already passed. Next
time maybe?
 If I don't contact you about that in september, you are welcome to contact
me to see what we can do. :-)

Den ons 13 feb. 2019 kl 23:15 skrev Chris Esposito <notifications@github.com
>:

> Yep, that's the first step. Important features are a High-speed USB 2.0
> transceiver (not full-speed, which is annoying 1/40th the speed of high
> speed!), fast ADC, DMA and good documentation/support.
> I remember reading about a MCU that had all of these features, but it cost
> around $7 per IC (compared to $2 for the Labrador 1.0's XMEGA32A4U).
> Once I've picked a part I'd need to make sure that the software is
> basically plausible.
> Next step would be to redesign the analog front-end. 6 resistors and half
> an LM324 won't cut it for higher frequency/bandwidth. Finally, all of the
> software - both embedded and fixing the desktop software to get it to work
> with the new hardware.
>
Wouldn't an embedded ARM M0 CPU be good for a more high end Labrador 2.0?
They are also popular in Maker space, like the ATXMEGA32 is. There are
great small embedded chips which would fit your description. Might have a
look at USB 3 for higher speed transfer, if possible in the cost frame.
Faster and more memory then the ATXMEGA32A4U 8-bit chip.
That is, something like ARM M0 core at 48MHz with DMA, 12 bit ADC and USB
and a nice price of about €1.16 for 100:
https://www.mouser.se/datasheet/2/389/stm32f070c6-956182.pdf

Might even show up as a USB memory stick where it simulated files that can
be used to read samples from, and write commands to configure the
Labrador.  Might make the software for hosts a bit easier to write?
The firmware for Microbit uses that approach to download and reprogram it,
open source that is.

Oh, so much fun project and so little time. :-)

> Completely doable, but would be a massive investment of time which I would
> honestly rather put towards marketing Labrador 1.0 - at least for 2019.
> It's a great product, but I only sell a few of them a week. I think a big
> part of that is because I'm not getting out there and letting people know
> that it exists. Both times it was reviewed in a magazine I sold 30-40 in
> the space of 2 weeks, and that was before the site redesign and eBay/Amazon
> listings (I was selling maybe 2-3 a week then, compared to 4-5 now). More
> marketing materials (e.g. a demonstration video on the website) and some
> tutorials/educational materials would help a lot too.
> At the end of the day, I'd honestly rather have 10,000 users with Labrador
> 1.0 than 2,000 users with Labrador 1.0 and another 2,000 users with
> Labrador 2.0. Both in terms of business, and in terms of making a
> difference in electronics education, the more people that have access to
> hardware, the better.
>
Know nothing abut marketing, sorry.  :-)

And yes, please ignore as I am just armchair coding here. But would be nice
to hear about what you might think about those thoughts. You that actually
have done the work with Labrador.

/Jackson

**Comment by EspoTek** [comment]
> Exactly what came to my mind... I am Physicist so let's brainstorm about that. With Labrador only, you can do power consumption measurement of e.g. a phone, a quadcopter, ... else?
> For education or school some additional sensors might be needed.

Yeah, agreed.  Labrador on its own is not super exciting.  An experiments book that you can use with a cheaply available, common kit from AliExpress/eBay (or perhaps even my own home-made kit, if I were to be a better businessman) would really drive home the educational possibilities of Labrador, and perhaps something that you eventually build up into a 3D printed robot would be even cooler.  You could really show off the advantages of having a scope there, with AC measurements on the power supply rails before/after R/L filtering, direct reads on sensors so people can actually understand what the code is doing and more.  Again, though, this all takes time.  Perhaps I should talk to my employer about working 4 days a week.  Not being entirely un-serious there.

> Currently I work in a technical highscool that started a new program 3 years ago. My boss did and still does at least 1 visit for promo a week (for 3 years now). I also do some, why not for Labrador also? Good thing here in Switzerland the Labrador cost about the price of 3-4 boxes of cigarettes - so it's really affordable.

Not quite sure what you mean here?  As in visit the high school and try to sell the Labrador to students?  Or teachers?  I've sold some boards at a group of guys who do Microcontroller stuff once, and that went pretty well (about 20 in one night, can't complain), but I'm just not quite sure how to break into education without first developing at least some basic teaching aids.

**Comment by drtrigon** [comment]
> Perhaps I should talk to my employer about working 4 days a week. Not being entirely un-serious there.

As I am studying (still!) and because of family, I am working 3 days per week only.

> Not quite sure what you mean here? As in visit the high school and try to sell the Labrador to students? Or teachers? I've sold some boards at a group of guys who do Microcontroller stuff once, and that went pretty well (about 20 in one night, can't complain), but I'm just not quite sure how to break into education without first developing at least some basic teaching aids.

Schools, Students and Teachers are good customers for sure, but I thought more general e.g. fab labs, maker spaces but also enthusiasts and public in general. My focus is on the promo, you have to go out there in order to reach the people. As often as possible, e.g. once a week.

**Comment by EspoTek** [comment]
> My 2nd year Computer Engineering students have a project that could be to design a prototype for a GUI in Java or something like that. To bad it is in the winter, so that project course has already passed. Next time maybe? If I don't contact you about that in september, you are welcome to contact me to see what we can do. :-)
Oh, that would be grest.  Please send me an email at admin@espotek.com so I can contact you about it in September (unless you don't mind posting your email on a public forum!)

> Wouldn't an embedded ARM M0 CPU be good for a more high end Labrador 2.0? They are also popular in Maker space, like the ATXMEGA32 is. There are great small embedded chips which would fit your description. Might have a look at USB 3 for higher speed transfer, if possible in the cost frame. Faster and more memory then the ATXMEGA32A4U 8-bit chip. That is, something like ARM M0 core at 48MHz with DMA, 12 bit ADC and USB and a nice price of about €1.16 for 100: https://www.mouser.se/datasheet/2/389/stm32f070c6-956182.pdf Might even show up as a USB memory stick where it simulated files that can be used to read samples from, and write commands to configure the Labrador. Might make the software for hosts a bit easier to write? The firmware for Microbit uses that approach to download and reprogram it, open source that is. Oh, so much fun project and so little time. :-)

Actually, the CPU and RAM don't matter much for Labrador - almost all of the actual processing is done on the user's PC and that's easily 100x the FLOPpage (technical term) of a 32-bit ARM Cortex M0.  Actually, if you look at the code for the XMEGA, the CPU does nothing apart from initialise the hardware and events system, acknowledge USB commands and calibrate the clock.  Everything is driven by the events system and DMA, so the most important specs are ADC sample rate and DMA throughput.  CPU-independent triggering is a necessity too.

I've looked at the STM32 series before and they are almost perfect for my purposes.  The F3 series can have up to 4 ADCs at 5Msps each (ie 20Msps total), but you cannot add USB 2.0 high-speed to it.  The F2 and F4 series allow you to add USB 2.0 High-speed PHYs, but the ADC only samples at 2Msps.  Both have plenty of DMA bandwidth, as well as built-in opamps and a 2-channel DAC.  Price is low too.  If only the F3 did USB HS!!!

Not quite sure how I'd work with files as the samples need to come in as a continuously updated stream.  At the moment, it uses a double ring buffer to store everything but to work with files I'd need to continuously update and stomp older files.  It does actually make sense to use HDD or SSD to increase the size of the buffer above and beyond the users' RAM though, and I could even add this to Labrador 1.0! 

> Know nothing abut marketing, sorry. :-) And yes, please ignore as I am just armchair coding here. But would be nice to hear about what you might think about those thoughts. You that actually have done the work with Labrador. /Jackson

Hey, you know as much about marketing as I do.  And probably more about coding, too (I'm still just a lowly grad with 8 months' real SWE experience and an electrical eng degree).  Definitely open to ideas in both discliplines.

Cheers,
~Chris

**Comment by EspoTek** [comment]
> As I am studying (still!) and because of family, I am working 3 days per week only.

So that's where you get the time to be EspoTek's #1 fanboy from!  :P
Seriously, though, surprised to hear that.  Always had the impression that you were much older than I am.

> Schools, Students and Teachers are good customers for sure, but I thought more general e.g. fab labs, maker spaces but also enthusiasts and public in general. My focus is on the promo, you have to go out there in order to reach the people. As often as possible, e.g. once a week.

You make a good point here.  Basically anyone who does electronics hobbyist stuff and doesn't already own a higher-end scope could get a huge amount of value out of a Labrador.  For fab labs etc., the choice is between 10 Labradors or a DS1052E.  The question is how to find all these people.

**Comment by kdwhite-ufl-edu** [comment]
This is Keith White, kdwhite@ufl.edu, expressing interest in your thread.  I am a semi-retired professor (University of Florida) who does some work with science fairs and this gives me contacts with the teachers whose students might benefit from Labradors. I will make enquiries and let you know if I learn anytning useful.  Thanks & Best Regards, Keith.

**Comment by drtrigon** [comment]
> So that's where you get the time to be EspoTek's #1 fanboy from! :P
Seriously, though, surprised to hear that. Always had the impression that you were much older than I am.

Just because I am still studying does not necessarily mean that I am young... ;)

> You make a good point here. Basically anyone who does electronics hobbyist stuff and doesn't already own a higher-end scope could get a huge amount of value out of a Labrador. For fab labs etc., the choice is between 10 Labradors or a DS1052E. The question is how to find all these people.

You don't need to have a complete list beforehand - just start somewhere e.g. look at http://3dprintingsystems.com/hackerspace-fablab/ found at https://www.google.com/search?channel=fs&q=fab+lab+makerspace+melborne etc. - and then by talking to the people you might get good hints what to do next - this is a step-by-step process. Also be prepared to visit some places multiple times, e.g. once a year.

**Comment by EspoTek** [comment]
> You don't need to have a complete list beforehand - just start somewhere e.g. look at http://3dprintingsystems.com/hackerspace-fablab/ found at https://www.google.com/search?channel=fs&q=fab+lab+makerspace+melborne etc. - and then by talking to the people you might get good hints what to do next - this is a step-by-step process. Also be prepared to visit some places multiple times, e.g. once a year.

Oh wow, they've got one at Docklands.  I go through there pretty much every weekday.  Will have a chat with the organisers and see what's doable...

> This is Keith White, [kdwhite@ufl.edu](mailto:kdwhite@ufl.edu), expressing interest in your thread. I am a semi-retired professor (University of Florida) who does some work with science fairs and this gives me contacts with the teachers whose students might benefit from Labradors. I will make enquiries and let you know if I learn anytning useful. Thanks & Best Regards, Keith.

Thank you do much, Keith.  I've received your email too.  Will talk abit it with you there.  :)

**Comment by FD0815** [comment]
Mandatory question: have you ever sent one to Dave Jones for a quick youtube review?

**Comment by EspoTek** [comment]
I haven't.  I spoke to him a couple of years back and he said to send it in, but just never got round to it.
