### ISSUE TITLE
If possible change the crowdsupply.com documentation url

### ISSUE THREAD

**Issue by hasorli** [EspoTek/Labrador#45]
The https://www.crowdsupply.com/espotek/labrador#details-top  documentation url : 
https://drive.google.com/drive/u/1/folders/0B7U0ulRLHf8cRVBkeFc2SHpUOGs
have moved to Github.  

The google search I did for "EspoTek Labrador" put the Crowdsupply as the first hit.  I suggest to make it easyer to find the dokumentation and code with the correct url from Crowdsupply.com

**Comment by EspoTek** [comment]
I can't edit the Crowd Supply page myself, but I'll send them an email.  :)
