### ISSUE TITLE
Window does not resize down enough

### ISSUE THREAD

**Issue by alxpettit** [EspoTek/Labrador#46]
Window does not resize far enough on the vertical axis. This may not seem like a big deal, but as someone who uses a ultraportable laptop with a screen smaller than the size of the window, it's a _serious_ problem.

![screenshot_2018-08-06_17-56-26](https://user-images.githubusercontent.com/28266167/43742992-10bb90b4-99a2-11e8-9fbf-1e670ada6d74.png)

Please fix this.

**Comment by alxpettit** [comment]
![screenshot_2018-08-06_18-03-10](https://user-images.githubusercontent.com/28266167/43743254-09f3e33e-99a3-11e8-9ad8-0c9c107a182b.png)

This is pretty much one of only two apps I can think of that actually won't work with 768 vertical pixels at standard DPMM. I don't think it's too much to ask? Let me know your thoughts.

**Comment by alxpettit** [comment]
Thanks! :)

**Comment by EspoTek** [comment]
Hey Alex.  I got a seat.  ;)

Have pushed a patch to GitHub that fixes the rendering on low-res displays - down to a minimum of 800x600!  It was originally designed to run at a minimum of 1024x768 before I broke it, so I guess that's an imprevement.  :)

The build server should make it within the next 30 mins or so, and when it's ready it'll be available here:
https://github.com/EspoTek/Labrador/releases

You'll want the AppImage from the "Continuous Release" section.

If you want to install it, you should be able to build from source (qmake, make, make install).
I tested it on my machine running Xorg/i3wm and it worked a treat.

I'll mark this issue as resolved for now.  If it doesn't work on your machine, just ~~install a new DE~~  reopen it and I'll see what I can do.

**Comment by EspoTek** [comment]
(And by the way, what was the other app that was broken on your machine)

**Comment by alxpettit** [comment]
Thanks! ^.^ The other software is [this](https://sourceforge.net/projects/aiboplus/). I guess they're maintaining a pretty massive build chain and sizable codebase and didn't really focus on the GUI much at all. It actually even went off the screen on my mother's much bigger laptop. I'll have to contact them about that and let them know at some point. :stuck_out_tongue_closed_eyes:

**Comment by alxpettit** [comment]
Hmm. Problem still seems to exist as of commit ddf60d5c63019eb27915d5d6a396d1374da071ce.

**Comment by alxpettit** [comment]
Tried compiling from source, and I got the same issue... (by the way, AppRun didn't let me run it without installing very willingly. I had to edit line 20 to `exec "$HERE/../bin/Labrador" "$@"` and edit my `LD_LIBRARY_PATH` to point to the directory containing `libdfuprog-0.9.so` to get it working. I'll probably open an issue about that as soon as I figure out exactly what went wrong and whether I was using anything in an unintended way...)

Anyway, the issue still existed after compiling from source. Which isn't surprising. Honestly, I think compiling it from source was more of me being bored than an actual debugging step.

**Comment by EspoTek** [comment]
Hmm, I'm not sure exactly what could be causing this.  I'm on a fairly stock version of Arch (also Xorg, but i3wm as window manager), and on my machine it renders at 800x600 without any issues.  I'm not sure of the specifics of DPI scaling either, but manually overriding the geometry should manually override it...

I'm about to go to sleep, but maybe try changing line 163 of MainWindow.cpp to `this->setGeometry(0, 0, 640, 480);`  Maybe even `this->setFixedSize(1366, 700)'?  
If you've got some weird scaling setting that might do it?
Possibly change your scaling settings, or full-screen it and un-fullscreen it again?

I'm not exactly sure what's causing this issue ; sorry.  
Either way, it should not be rendering at 1024x768.  That patch changed the minimum resolution down to 800x600.

**Comment by EspoTek** [comment]
Actually, just thought of a possible issue...
Pull the latest version.  It *may* contain a fix.

**Comment by alxpettit** [comment]
Just pulled and recompiled. No dice. :(

I'll go ahead and check the latest binary build, in case my `make clean` call left some old objects somewhere or something.

**Comment by alxpettit** [comment]
If it helps with debugging (seems like our best bet at this stage), I could go ahead and try to recreate the issue in a virtual machine with a minimal standard Arch setup, and maybe with a few other distros. Once I get something with the problem, I could even send you the whole virtual machine file so you can do diagnostics. Would that help?

**Comment by EspoTek** [comment]
I think it might be easier to just try it in a different desktop environment.  ctrl-alt-F2 will let you log into a second virtual terminal.

**Comment by alxpettit** [comment]
Eh, it could be almost anything at this point, down to Xorg configs or bugs in specific package versions. Plus, I like to keep my setup clean. Installing packages not natively needed except for one test would leave lots of crud around my system to clean up. :stuck_out_tongue:

**Comment by EspoTek** [comment]
Or perhaps adding a 68 pixel tall widget to the bottom of the Main Window would at least let you see the whole screen?  Should be easy to do graphically in Qt Creator.  Make sure it's fixed-size.  And ignore the mess...

**Comment by alxpettit** [comment]
I just recreated the bug in a Xubuntu VM. Definitely not a fluke.

**Comment by alxpettit** [comment]
Lubuntu won't display properly on my machine in a VM. I vaguely remember having this issue before. Not sure what to do about it, but unfortunately I won't be able to use it to test your build. :(

**Comment by alxpettit** [comment]
I've got some bad news...

![screenshot_2018-08-07_22-51-53](https://user-images.githubusercontent.com/28266167/43813639-8d3c4a00-9a94-11e8-83ef-5704d6ba0a1b.png)

Um... now what?

**Comment by alxpettit** [comment]
I'm doing some qt API research. I'll let you know if I find anything!

**Comment by alxpettit** [comment]
Yep. I fixed your problem.

**Comment by alxpettit** [comment]
Actually, it's such a small change that it's not needed. Change lines 18 and 19 in `mainwindow.ui` to correct minimum width.

I may have a few other pull requests though! If you don't mind that is.

**Comment by EspoTek** [comment]
Oh, would love a PR.  What did you do to get it working in the end?  Just changed the .ui?  It's weird; setGeometry should have overwritten that setting as it was called after the UI initialisation.

**Comment by alxpettit** [comment]
Yeah. Changing the `.ui` is all I needed to do.

**Comment by EspoTek** [comment]
Too easy.  I can patch that tonight.

**Comment by EspoTek** [comment]
3 days later...

Finall had the opportunity to sit down and fix the issue.
I'll mark this closed for now.  Feel free to pass on your other ideas.  I'd love to hear them.  :)

Cheers,
~Chris
