### ISSUE TITLE
Add display scaling settings to main window

### ISSUE THREAD

**Issue by drtrigon** [EspoTek/Labrador#49]
It would be very useful if both graph axes ("Time Window" and "Vmax"/"Vmin") could be easily changed in the main window (allowing for zooming out also). Simplest would be to just move everything from "Oscilloscope > Range > Enter Manually" to the main window. May be also add sliders or something.

**Comment by EspoTek** [comment]
Hey man.  Great to hear from you.  It's nice to see someone getting so much use out of the project!

I added this feature on the way home from work.  Check the latest build.  :)
Oscilloscope->Show Range Dialog on Main Page.

**Comment by drtrigon** [comment]
That was fast! Thanks a lot!

> Hey man. Great to hear from you. It's nice to see someone getting so much use out of the project!

It is a cool project! Thanks also for your ongoing and fast support!

**Comment by EspoTek** [comment]
Haha, gotta make an effort for Dr. Tigon.  :)

**Comment by drtrigon** [comment]
Work very nice and is extremely useful, thanks!
