### ISSUE TITLE
Cannot find a pinout diagram

### ISSUE THREAD

**Issue by timhughes** [EspoTek/Labrador#6]
Any chance you can do a diagram of what the headers are on the new model similar to the original diagram on the croud-supply page 

https://www.crowdsupply.com/img/5074/lab-backer-edition-5_jpg_project-body.jpg

or point me in the right direction

**Comment by EspoTek** [comment]
Hi Tim.  Pinout is included alongside documentation here:
https://drive.google.com/open?id=0B7U0ulRLHf8cRVBkeFc2SHpUOGs

Not quite as pretty as the Crowd Supply photo, but currently focusing on software errors before diagram prettyficiation.  :)

~Chris

**Comment by timhughes** [comment]
thanks
