### ISSUE TITLE
Missing calibration data (Windows)

### ISSUE THREAD

**Issue by OttoMan28** [EspoTek/Labrador#70]
Every time i start the Labrador windows application, i'm told that the calibration data is not detected.
Its like its not storing the calibration data after a calibration.

![skaermbillede 2019-03-06 18 25 42](https://user-images.githubusercontent.com/47725441/53900634-48331200-403d-11e9-8c13-65a03c4b8f34.png)

**Comment by EspoTek** [comment]
Does this issue still exist when running as admin?  IIRC, it stores the settings in an .INI file in the same directory as the executable (which in theory should be mirrored on Windows to ProgramData but may not be).  

That said, just using a different constructor for QSettings would remove this problem entirely and is a 2-minute fix.  I'll have a look at it when I next have time.

**Comment by OttoMan28** [comment]
The 'run as admin' did the trick :-)

Thanks

**Comment by EspoTek** [comment]
Hey, don't say "thanks" yet.  That's not a fix, it's a workaround.  :)

Will need to fix the remote builds on Windows and then patch the settings reader before I can accept a thanks.  :P

**Comment by EspoTek** [comment]
Well, the hard bit is done here.  Windows remote builds are fixed (barring the old source code versions)!

**Comment by EspoTek** [comment]
https://github.com/EspoTek/Labrador/commit/5cc7c9425d70f3c795ba5785a581dcd047a8dd5a

**Comment by EspoTek** [comment]
Does that work for you?

**Comment by EspoTek** [comment]
Closing this issue now.  Confirmed working on Windows 10 x64 machine.
