### ISSUE TITLE
Fix reference to private library in kicad project

### ISSUE THREAD

**Issue by tardate** [EspoTek/Labrador#9]
Brilliant work Chris, and I love how you've jumped in feet first to making the hardware and software open.

I was able to review the PCB in kicad with no major issues, although eeschema does complain about one library reference that is not in the repo: `LibName31=C:/Users/Esposch/Documents/KiCAD/ESPO_PART`

I haven't noticed what if any impact this has, but it probably needs cleaning up one way or another.

**Comment by EspoTek** [comment]
Hey Paul.

Finally fixed the issue, just 6 months later.  No idea why it wasn't fixed earlier, only took 2 minutes...
Mind you, I think my cortisol levels back in July were about 10x the legal limit.

Looks like the library contained the dual transistor IC that buffers inputs the logic analyzer.

Thanks for the document you wrote up, by the way.
It keeps popping up whenever I Google the words "EspoTek Labrador", and I'm sure it's extremely helpful for new players.

Cheers
~Chris
