### ISSUE TITLE
fix unmarked values in bom

### ISSUE THREAD

**Issue by NoSkillsToPayTheBillz** [EspoTek/Labrador#94]
The resistors and caps aren’t marked and one of the ic. it’s kinda a mess in the bom can you fix it if you got some time. I found a old closed issue about it but it never got fixed.

**Comment by EspoTek** [comment]
Hey, so short answer is that I can look into this, but it's currently not a high priority.  I'll leave this issue open until it's fixed, but I'd expect that to take a few months at least.
