### ISSUE TITLE
After exiting X-Y mode there are spurious lines on the display

### ISSUE THREAD

**Issue by StarNamer** [EspoTek/Labrador#97]
Screenshot shows the effect. The only way to clear it seems to be to exit and restart. I'm using the win32 version of 18/Aug/2019 (ba4d61d).
![image](https://user-images.githubusercontent.com/1997874/63392342-196fe480-c3ae-11e9-8354-f979d8b8bfbd.png)

**Comment by EspoTek** [comment]
Apologies, I thought I'd fixed this and submitted a patch.  Either way, I know the exact cause of this issue, so should be able to submit a patch on the weekend.

**Comment by EspoTek** [comment]
Fixed in a4471c6.
https://github.com/EspoTek/Labrador/commit/a4471c6ee6b38956694e603f8eb3f6a837284208
